### ISSUE TITLE
#2. A cell that takes the input shape, calls a dummy "cleaning/feature engineering" function on it ...

### ISSUE THREAD

**Issue by loketi** [Quantyra/kaggle-icr-challenge#2]
A cell that takes the input shape, calls a dummy "cleaning/feature engineering" function on it and then calls a dummy "inference" function on it which generates random predictions for each class / row.

**Comment by dfredriksen** [comment]
How is this coming along @scientistkev ? We have the real cleaning / engineering features so the first part of this is already done, but we could use a dummy output model, such as a random classifier, to put a baseline submission up for us.

**Comment by dfredriksen** [comment]
I took care of this and implemented a naive logistic regression model to have a fully functioning pipeline.
